def get_trend_wordlist():
    return ["VR/AR/MR-Marketing Smart Glasses/ AR Assistants", "VR/AR/MR-based Training", "AR Payment",
            "Biometrischer Pass",
            "Biometrische Authentifizierung", "Biometrische Daten", "Blockchain", "Smart Contracts",
            "Kryptowährungen",
            "Low Code", "No Code", "Personal ID", "Machine ID", "Dezentrale ID-Services", "Highspeed-Mobilfunkknetze",
            "Dezentrale Energienetze",
            "Smart Grids", "Personal Data", "Data Ownership", "Cloud Services", "Banking-as-a-Service",
            "Data-as-a-Service",
            "Information-as-a-Service",
            "Knowledge-as-a-Service", "Human-as-a-Service", "Instant Payment", "Car Payment", "Machine Payment",
            "Micro Payment", "PSD2", "Robotic Process Automation",
            "Vollautomatische Produktion", "Gesellschaftliche Individualisierung", "Wirtschaftliche Individualisierung",
            "Politische Individualisierung", "Pay-Per-Use",
            "Condition Monitoring", "Predictive Maintenance", "Smart Home", "Ambient Assisted Living", "Deep Learning",
            "Natural Language Processing", "NLP", "Fraud Detection",
            "Machine Learning", "Neuronale Netze", "Robotic Proces Automation", "Drohnen", "Connected Car",
            "Autonomes Fahren",
            "Wasserstoffautos", "Elektromobilität",
            "Ökologischer Fußabdruck", "Nachhaltiges Einkaufsverhalten", "Greenwashing", "Plattformökosysteme",
            "Digitale Geschäftsmodelle", "Quantenverschlüsselung", "Quantum Annealing",
            "Quantum Simulation", "Smart Regions", "Progressive Provinzen", "Glokalisierung", "Robotic Teaching",
            "Software Roboter", "Asset Sharing", "Co-Working", "Talent Sharing", "Shared Computing",
            "Shared Data", "Shared Knowledge", "Crowd Saving", "Crowd Funding", "Multi-Aging-Kultur", "Smart Economy",
            "Smart People", "Smart Governance", "Smart Mobility", "Smart Environment",
            "Smart Living", "Voice Commerce", "Virtual Reality Store", "Digitale Lieferkette", "Ultra-Personalisierung",
            "Dynamisches Pricing", "Location-based Services", "Data Analytics", "Smart Data",
            "Physische Verstädterung", "Funktionale Verstädterung", "Soziale Verstädterung",
            "Demographische Verstädterung", "java", "python", "spark", "hadoop", "tensorflow",
            "bootstrap", "springboot", "spring", "Angular", "React", "Automic", "linux", "Windows", "Host", "z/os",
            "mainframe", "data",
            "Verdichtung des Städtesystems"]
